version: "3"
services:
  laravel:
    container_name: laravel
    image: bitnami/laravel
    stdin_open: true
    tty: true
    ports:
      - 8080:8000
    volumes:
      - ./project:/app

  mysql:
    image: mysql
    container_name: mysql
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "admin"